# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestrike_app', '0003_auto_20190721_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='game',
            name='points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
    ]
