# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestrike_app', '0005_auto_20190721_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(default='http://10.3.17.246:8000/', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
        
    ]
